name: Update awesome-stars

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  awesome-stars:
    name: update awesome-stars
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - run: pip install starred
      - name: Update star list
        run: starred --username ${{ github.repository_owner }} --sort --token ${{ secrets.GITHUB_TOKEN }} > README.md
      - uses: EndBug/add-and-commit@v7
        with:
          add: '["README.md"]'
          author_name: "GH Bot"
          author_email: "bot@github.com"
          message: "chore: recap update"
          pull_strategy: "--no-ff"
